# Generated by Django 3.2.6 on 2021-08-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('prompts', models.CharField(blank=True, max_length=400)),
                ('keywords', models.CharField(blank=True, max_length=100)),
                ('cons', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Positive', 'Positive'), ('Negative', 'Negative')], default='Negative', max_length=15)),
            ],
        ),
    ]
