# Generated by Django 3.2.6 on 2021-08-11 09:58

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pic',
            field=models.ImageField(blank=True, default='no image', null=True, upload_to=account.models.get_profile_image_filepath),
        ),
    ]
